// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ColorPicker: typeof import('./src/components/ColorPicker.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ExportImage: typeof import('./src/components/ExportImage.vue')['default']
    FieldsCustom: typeof import('./src/components/FieldsCustom.vue')['default']
    JsonCanvas: typeof import('./src/components/JsonCanvas.vue')['default']
    LayoutCustom: typeof import('./src/components/LayoutCustom.vue')['default']
    LayoutOptions: typeof import('./src/components/LayoutOptions.vue')['default']
    NodeDialog: typeof import('./src/components/NodeDialog.vue')['default']
    SearchInput: typeof import('./src/components/SearchInput.vue')['default']
    VueCodeMirror: typeof import('./src/components/VueCodeMirror.vue')['default']
  }
}
